# Generated by Django 2.1.2 on 2018-12-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Initi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mub_name', models.CharField(max_length=250)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=250)),
                ('progress_num', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('final_rate', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ar', models.CharField(max_length=250)),
                ('week_no', models.CharField(max_length=250)),
                ('ready', models.BooleanField(default=0)),
                ('mub_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=500)),
                ('owner_risk', models.CharField(max_length=250)),
                ('probability', models.CharField(max_length=250)),
                ('influence', models.CharField(max_length=250)),
                ('plan', models.TextField()),
                ('mub_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=250)),
                ('ratio', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
                ('mub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.CreateModel(
            name='Supports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=500)),
                ('mub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi')),
            ],
        ),
        migrations.AddField(
            model_name='mainstage',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports'),
        ),
        migrations.AddField(
            model_name='goals',
            name='mub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='mub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Initi'),
        ),
    ]
