# Generated by Django 2.1.2 on 2018-12-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
