# Generated by Django 2.1.2 on 2018-12-08 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_mainstage_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 3, 13, 49, 64434)),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Stages'),
        ),
    ]
