# Generated by Django 2.1.2 on 2018-12-08 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_auto_20181208_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 3, 16, 55, 996363)),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='stage',
            field=models.CharField(max_length=250),
        ),
    ]
