# Generated by Django 2.1.2 on 2018-12-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_auto_20181208_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstage',
            name='report',
        ),
        migrations.DeleteModel(
            name='MainStage',
        ),
    ]
