# Generated by Django 2.1.2 on 2018-12-08 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0005_auto_20181208_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_num', models.IntegerField(default=0)),
                ('info', models.TextField()),
                ('final_rate', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 12, 8, 3, 38, 43, 39179))),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Reports')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.Stages')),
            ],
        ),
    ]
