# Generated by Django 2.1.2 on 2018-12-08 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_auto_20181208_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 14, 18, 7, 230714)),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='stage',
            field=models.CharField(max_length=250),
        ),
    ]
