# Generated by Django 2.1.2 on 2019-02-04 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0010_auto_20181208_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstage',
            name='end_date',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 21, 37, 18, 363763)),
        ),
    ]
