# Generated by Django 2.1.2 on 2019-02-05 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0011_auto_20190204_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 4, 30, 32, 635690)),
        ),
    ]
