# Generated by Django 2.1.2 on 2019-02-05 05:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0013_auto_20190205_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initi',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 8, 0, 50, 453689)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
