# Generated by Django 2.1.2 on 2019-02-05 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0014_auto_20190205_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 8, 15, 55, 171819)),
        ),
    ]
